### ISSUE TITLE
Testfile "File001.ifc" in branch "alb001_alignment-in-spatial-structure" should pass but fails

### ISSUE THREAD

**Issue by apinzenoehler** [buildingSMART/ifc-gherkin-rules#11]
According to README.md in https://github.com/buildingSMART/ifc-gherkin-rules/tree/alb001_alignment-in-spatial-structure/test/ALB001 testfile should pass.

It fails in https://validate.buildingsmart.org with error report below:

    For instance:
        #26 = IFCALIGNMENT('0y2hQsQKfAqxEufY7Z_1jL', $, 'RS02 short VG', '12d Alignment String', 'natural clothoid', $, $, $, $);

    Wrong number of attributes on instance with id #26 expected 8 got 9
    For instance:
        #28 = IFCALIGNMENTHORIZONTAL('1FahSvf2z8YeREQCzieDuo', #2, 'Horizontal Alignment', '12d Horizontal Alignment', $, $, $, 0., (#29, #31, #33));

    Wrong number of attributes on instance with id #28 expected 7 got 9
    For instance:
        #35 = IFCALIGNMENTVERTICAL('3gA2mMqFX0xfZWiXfZxgI6', #2, 'Vertical Alignment', '12d Vertical Alignment', $, $, $, (#36, #37, #38, #39, #40));

    Wrong number of attributes on instance with id #35 expected 7 got 8

BR Andreas

**Comment by aothms** [comment]
Every test file in the ifc-gherkin-rules assumes should have a valid syntax and schema. We have dedicated test files for the other validation steps. So the file needs to be corrected. So that also applies to #8, we'll likely still expand the readme with some additional content, but only IA IP (to be merged as simply "(conformance) rules") are relevant to this repo.

**Comment by JTurbakiewicz** [comment]
Implemented in [03a855](https://github.com/buildingSMART/ifc-gherkin-rules/pull/13/commits/03a8551077efad773b8da42d51c5c9fedd0fdded).

The branch is still under development/review, but that error should be mitigated now.
