### ISSUE TITLE
IfcTextLiteralWithExtent failing check IFC102

### ISSUE THREAD

**Issue by jmirtsch** [buildingSMART/ifc-gherkin-rules#279]
There is a validation check that nominates IfcTextLiteral as deprecated.
https://github.com/buildingSMART/ifc-gherkin-rules/blob/31df6539adce05ed9a5b4966ac3ee804b2895791/features/IFC102_Absence-of-deprecated-entities.feature#L42

It seems that IfcTextLiteral was deprecated in IFC4 (https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcTextLiteral.htm), proposed to be made abstract.
IfcTextLiteralWithExtent was not deprecated.  https://standards.buildingsmart.org/IFC/RELEASE/IFC4/FINAL/HTML/link/ifctextliteralwithextent.htm

In IFC4.3, IfcTextLiteral is included in RV and ABV
https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcTextLiteral.htm
Although IfcTextLiteralWithExtent is not tagged.
https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcTextLiteralWithExtent.htm

We are using IfcTextLiteralWithExtent representation in export for 4.3.   But it triggers 
https://github.com/buildingSMART/ifc-gherkin-rules/blob/31df6539adce05ed9a5b4966ac3ee804b2895791/features/IFC102_Absence-of-deprecated-entities.feature#L42

Can this rule please be adjusted to not flag non compliance for IfcTextLiteralWithExtent
The nomination of IfcTextLiteralWithExtent for mvds rather than the base class would seem appropriate.

Thanks,

Jon

**Comment by aothms** [comment]
Thanks for bringing this up. I think there have been other cases in IFC4 implying: "deprecated for direct instantiation, intended to become abstract in the future".

I see two options:

- For me this is not standard usage of the term "deprecation". So an option is to remove this deprecation from the schema altogether.
- Alternatively we make the list checked as exact types, instead of type + subtypes. Most of these items are leaf entities anyway. This is probably the safest way forward.

@Ghesselink I see there is also selects in the list: a select can never be instantiated so can't be in this list, also this one is already deleted in 4.3

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcpresentationstyleselect.htm

**Comment by Ghesselink** [comment]
Fix merged https://github.com/buildingSMART/ifc-gherkin-rules/pull/282
